### ISSUE TITLE
Aux folder name incompatible with Windows

### ISSUE THREAD

**Issue by ntardiff** [asoroosh/xDF#2]
It turns out that you cannot create a folder named Aux on Windows, so the repository can't be cloned and the Aux directory can't be extracted from the zip file--you must extract all the files separately and then create a new directory not named aux. Is there any chance that directory could be renamed?

Thanks,
Nathan

**Comment by asoroosh** [comment]
Hi Nathan, 
I just renamed the directory `Aux` to `mis` and updated the repo. Try again and let me know, please.

**Comment by ntardiff** [comment]
It works now. Thanks!
